plot(continent, gdp)
OLS_Final = lm(gdp ~ trade + area + pop + continent)
summary(OLS_Final)
stargazer(OLS, OLS_Final, type = "text", style = "all")
final = ivreg(gdp ~ trade + area + pop + continent | area + pop + trade + landlock + neighbors + continent)
stargazer(final, type = "text", style = "all")
summary(final)